server:
  port: 8080
spring:
  profiles:
    active: cluster

---
spring:
  profiles: single
  rabbitmq:
    host: 192.168.254.151
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated

---
spring:
  profiles: cluster
  rabbitmq:
    addresses: 192.168.254.152:5672, 192.168.254.153:5672, 192.168.254.154:5672
    username: admin
    password: 123