spring:
  profiles:
    active: cluster

server:
  port: 8080

---
# spring连接单台Redis配置
spring:
  profiles: single

  redis:
    database: 0
    timeout: 3000
    host: 192.168.254.104
    port: 6379
    password: jiangyue

    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000

---
# spring连接Redis哨兵模式配置
spring:
  profiles: sentinel

  redis:
    database: 0
    timeout: 3000
    password: jiangyue

    sentinel:
      master: mymaster
      nodes: 192.168.254.104:26379, 192.168.254.104:26380, 192.168.254.104:26381

    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 1000

---
# spring连接Redis集群配置
spring:
  profiles: cluster

  redis:
    database: 0
    timeout: 3000
    password: jiangyue
    cluster:
      nodes: 192.168.254.101:8001, 192.168.254.101:8004, 192.168.254.102:8002, 192.168.254.102:8005, 192.168.254.103:8003, 192.168.254.103:8006
      max-redirects: 3
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000